-- MySQL Script generated by MySQL Workbench
-- Sat May 25 15:36:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET @idSchemaVersion = '';
SET @change_number = 1;
SET @version = '1.0';
SET @applied = current_timestamp();
SET @description = 'first db create';
SET @file = 'test';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Podjetje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Podjetje` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Podjetje` (
  `idPodjetje` BINARY(16) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `tax_num` VARCHAR(45) NOT NULL,
  `registration_number` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `taxpayer` TINYINT(1) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idPodjetje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Izdelek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Izdelek` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Izdelek` (
  `idIzdelek` BINARY(16) NOT NULL,
  `barcode` VARCHAR(14) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `vat` DECIMAL(5,2) NOT NULL,
  `stock` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idIzdelek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InternalIzdelek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InternalIzdelek` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InternalIzdelek` (
  `idInternalIzdelek` BINARY(16) NOT NULL,
  `internal_id` VARCHAR(4) NOT NULL,
  `name` VARCHAR(1000) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `vat` DECIMAL(5,2) NOT NULL,
  `stock` INT NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  PRIMARY KEY (`idInternalIzdelek`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SchemaVersion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SchemaVersion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SchemaVersion` (
  `idSchemaVersion` BINARY(16) NOT NULL,
  `change_number` INT NOT NULL,
  `version` VARCHAR(30) NOT NULL,
  `applied` DATETIME NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  `file` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSchemaVersion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Racun`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Racun` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Racun` (
  `idRacun` BINARY(16) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `total_val` DECIMAL(10,2) NOT NULL,
  `deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `created` TIMESTAMP NOT NULL,
  `modified` TIMESTAMP NULL,
  `issuer_id` BINARY(16) NOT NULL,
  `customer_id` BINARY(16) NULL,
  PRIMARY KEY (`idRacun`),
  INDEX `fk_Racun_Podjetje_idx` (`customer_id` ASC),
  INDEX `fk_Racun_Podjetje1_idx` (`issuer_id` ASC),
  CONSTRAINT `fk_Racun_Podjetje`
    FOREIGN KEY (`customer_id`)
    REFERENCES `mydb`.`Podjetje` (`idPodjetje`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Racun_Podjetje1`
    FOREIGN KEY (`issuer_id`)
    REFERENCES `mydb`.`Podjetje` (`idPodjetje`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RacunIzdelki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RacunIzdelki` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RacunIzdelki` (
  `idRacun` BINARY(16) NOT NULL,
  `idIzdelek` BINARY(16) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idRacun`, `idIzdelek`),
  INDEX `fk_RacunIzdelki_Izdelek1_idx` (`idIzdelek` ASC),
  CONSTRAINT `fk_RacunIzdelki_Racun1`
    FOREIGN KEY (`idRacun`)
    REFERENCES `mydb`.`Racun` (`idRacun`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_RacunIzdelki_Izdelek1`
    FOREIGN KEY (`idIzdelek`)
    REFERENCES `mydb`.`Izdelek` (`idIzdelek`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RacunInternalIzdelki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`RacunInternalIzdelki` ;

CREATE TABLE IF NOT EXISTS `mydb`.`RacunInternalIzdelki` (
  `idInternalIzdelek` BINARY(16) NOT NULL,
  `idRacun` BINARY(16) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idInternalIzdelek`, `idRacun`),
  INDEX `fk_RacunInternalIzdelki_Racun1_idx` (`idRacun` ASC),
  CONSTRAINT `fk_RacunInternalIzdelki_InternalIzdelek1`
    FOREIGN KEY (`idInternalIzdelek`)
    REFERENCES `mydb`.`InternalIzdelek` (`idInternalIzdelek`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_RacunInternalIzdelki_Racun1`
    FOREIGN KEY (`idRacun`)
    REFERENCES `mydb`.`Racun` (`idRacun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

INSERT INTO SchemaVersion VALUES (@idSchemaVersion,@change_number,@version,@applied,@description,@file);

DELIMITER $$

USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Podjetje_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Podjetje_BEFORE_UPDATE` BEFORE UPDATE ON `Podjetje` FOR EACH ROW
BEGIN
	SET NEW.modified = current_timestamp(); 
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Izdelek_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Izdelek_BEFORE_UPDATE` BEFORE UPDATE ON `Izdelek` FOR EACH ROW
BEGIN
	SET NEW.modified = current_timestamp(); 
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`InternalIzdelek_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`InternalIzdelek_BEFORE_UPDATE` BEFORE UPDATE ON `InternalIzdelek` FOR EACH ROW
BEGIN
	SET NEW.modified = current_timestamp(); 
END$$


USE `mydb`$$
DROP TRIGGER IF EXISTS `mydb`.`Racun_BEFORE_UPDATE` $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Racun_BEFORE_UPDATE` BEFORE UPDATE ON `Racun` FOR EACH ROW
BEGIN
	SET NEW.modified = current_timestamp(); 
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
